package com.lablocator.service.ai;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.List;
import java.util.Map;

/**
 * Calls the Google Gemini REST API to analyse a medical lab report.
 *
 * <p>Improvements over the original:
 * <ul>
 *   <li>Correct model endpoint (gemini-2.0-flash via v1beta)</li>
 *   <li>Explicit JSON schema enforced via system instruction + output format directive</li>
 *   <li>Configured timeout so a slow API call never hangs the thread indefinitely</li>
 *   <li>Text truncation to stay within the model's token budget (~30 k chars ≈ 7 k tokens)</li>
 *   <li>Response parsed into {@link ReportAnalysis} so callers get a typed object, not raw text</li>
 *   <li>Robust JSON extraction that strips markdown fences if Gemini wraps output in ```json```</li>
 *   <li>Safety settings tuned so medical content is not incorrectly blocked</li>
 * </ul>
 */
@Service
public class GeminiService {

    private static final Logger log = LoggerFactory.getLogger(GeminiService.class);

    /**
     * Gemini 2.5 Flash (v1beta) with thinking DISABLED.
     *
     * <p>Why this exact combination:
     * <ul>
     *   <li>gemini-2.0-flash: free-tier quota = 0 on this key — unusable</li>
     *   <li>gemini-2.5-flash default: thinking model — reasoning tokens eat the output budget
     *       causing truncated JSON even at maxOutputTokens=8192</li>
     *   <li>gemini-2.5-flash + thinkingBudget=0: thinking is disabled, all output tokens
     *       go to the actual response, free-tier quota available ✔</li>
     *   <li>v1beta: supports both responseMimeType and thinkingConfig ✔</li>
     * </ul>
     */
    private static final String GEMINI_URL_TEMPLATE =
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=%s";

    /** Input text cap: keeps input tokens well below the 1M limit and leaves room for the prompt */
    private static final int MAX_TEXT_CHARS = 15_000;

    /**
     * The JSON schema Gemini must follow. Embedding it directly in the prompt
     * is the most reliable way to enforce structured output with the REST API.
     */
    private static final String JSON_SCHEMA = """
            {
              "patientSummary": "<string: 1-2 sentences a non-medical person can understand>",
              "riskLevel": "<one of: Normal | Borderline | Abnormal | Critical>",
              "keyFindings": [
                {
                  "name": "<marker name>",
                  "value": "<measured value>",
                  "unit": "<unit, or empty string>",
                  "normalRange": "<normal range, or empty string>",
                  "status": "<one of: Normal | High | Low | Critical>"
                }
              ],
              "abnormalFindings": [
                {
                  "marker": "<name>",
                  "value": "<measured value>",
                  "concern": "<plain-English explanation of the concern>",
                  "severity": "<one of: Mild | Moderate | Severe>"
                }
              ],
              "suggestions": [
                "<actionable lifestyle or dietary suggestion for the patient>"
              ],
              "followUpTests": [
                "<name of recommended follow-up test>"
              ],
              "disclaimer": "This analysis is generated by AI and is for informational purposes only. Please consult a qualified doctor before making any health decisions."
            }
            """;

    private static final String SYSTEM_INSTRUCTION = """
            You are MedInsight, an expert medical AI assistant that helps patients understand their lab reports.
            Your role is STRICTLY to interpret and explain the provided lab report text.
            Rules you MUST follow:
            1. Respond ONLY with a single, valid JSON object. No markdown, no explanation outside JSON.
            2. Use simple, compassionate, non-technical language a patient can understand.
            3. Never diagnose or prescribe — only explain and suggest consulting a doctor.
            4. If a value is clearly normal, still list it in keyFindings with status "Normal".
            5. Only list a finding in abnormalFindings if its value is outside the reference range.
            6. The "disclaimer" field must always be exactly: "This analysis is generated by AI and is for informational purposes only. Please consult a qualified doctor before making any health decisions."
            7. If insufficient data is present to fill a list, return an empty array [].
            """;

    @Value("${gemini.api.key}")
    private String apiKey;

    private final RestTemplate restTemplate;
    private final ObjectMapper objectMapper;

    public GeminiService(ObjectMapper objectMapper) {
        this.objectMapper   = objectMapper;
        this.restTemplate   = buildRestTemplate();
    }

    // ── Public API ────────────────────────────────────────────────────────────

    /**
     * Sends the PDF text to Gemini and returns a parsed {@link ReportAnalysis}.
     *
     * @param reportText raw text extracted from the PDF
     * @return structured analysis
     * @throws ReportAnalysisException if the API call fails or the response cannot be parsed
     */
    public ReportAnalysis analyzeReport(String reportText) {
        String truncated = truncate(reportText);
        String prompt    = buildPrompt(truncated);
        String rawJson   = callGemini(prompt);
        return parseResponse(rawJson);
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    private String truncate(String text) {
        if (text == null) return "";
        return text.length() > MAX_TEXT_CHARS ? text.substring(0, MAX_TEXT_CHARS) : text;
    }

    private String buildPrompt(String reportText) {
        return SYSTEM_INSTRUCTION + "\n\n"
                + "Return ONLY a JSON object that matches this exact schema:\n"
                + JSON_SCHEMA + "\n\n"
                + "Lab Report Text:\n---\n" + reportText + "\n---";
    }

    private String callGemini(String prompt) {
        String url = String.format(GEMINI_URL_TEMPLATE, apiKey);

        // Safety settings — lower thresholds so medical content is not incorrectly blocked
        List<Map<String, String>> safetySettings = List.of(
                Map.of("category", "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold", "BLOCK_ONLY_HIGH"),
                Map.of("category", "HARM_CATEGORY_HARASSMENT",        "threshold", "BLOCK_ONLY_HIGH"),
                Map.of("category", "HARM_CATEGORY_HATE_SPEECH",       "threshold", "BLOCK_ONLY_HIGH")
        );

        // responseMimeType forces pure JSON output (no markdown fences) — v1beta feature.
        // thinkingConfig disables internal reasoning so all output tokens go to real content.
        Map<String, Object> generationConfig = Map.of(
                "temperature",       0.1,
                "topP",              0.8,
                "maxOutputTokens",   8192,
                "responseMimeType",  "application/json",
                "thinkingConfig",    Map.of("thinkingBudget", 0)   // disable thinking tokens
        );

        // Single, clean request body — full prompt in contents
        Map<String, Object> requestBody = Map.of(
                "contents", List.of(
                        Map.of("parts", List.of(Map.of("text", prompt)))
                ),
                "safetySettings",   safetySettings,
                "generationConfig", generationConfig
        );

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);

        try {
            @SuppressWarnings("unchecked")
            Map<String, Object> response = restTemplate.postForObject(
                    url,
                    new HttpEntity<>(requestBody, headers),
                    Map.class
            );
            return extractText(response);
        } catch (Exception e) {
            log.error("Gemini API call failed: {}", e.getMessage(), e);
            throw new ReportAnalysisException("AI service is temporarily unavailable. Please try again later.", e);
        }
    }

    @SuppressWarnings("unchecked")
    private String extractText(Map<String, Object> response) {
        try {
            var candidates = (List<?>) response.get("candidates");
            if (candidates == null || candidates.isEmpty()) {
                log.warn("Gemini returned no candidates. Full response: {}", response);
                throw new ReportAnalysisException("AI returned an empty response.");
            }
            var first   = (Map<String, Object>) candidates.get(0);

            // Warn if Gemini stopped early due to token limit
            String finishReason = (String) first.get("finishReason");
            if ("MAX_TOKENS".equals(finishReason)) {
                log.warn("Gemini response was cut off at MAX_TOKENS — consider reducing report size or prompt length");
            }

            var content = (Map<String, Object>) first.get("content");
            var parts   = (List<?>) content.get("parts");
            var text    = (String) ((Map<?, ?>) parts.get(0)).get("text");

            if (text == null || text.isBlank()) {
                throw new ReportAnalysisException("AI returned a blank response.");
            }
            return stripMarkdownFences(text);
        } catch (ReportAnalysisException e) {
            throw e;
        } catch (Exception e) {
            log.error("Failed to extract text from Gemini response: {}", response, e);
            throw new ReportAnalysisException("Failed to parse AI response.", e);
        }
    }

    /**
     * Strips markdown code fences that Gemini sometimes wraps around JSON output.
     *
     * <p>Handles three cases:
     * <ul>
     *   <li>No fence:           returns text as-is</li>
     *   <li>Opening + closing:  extracts content between the two fences</li>
     *   <li>Opening only (truncated response): strips just the first line</li>
     * </ul>
     */
    private String stripMarkdownFences(String text) {
        String trimmed = text.strip();
        if (!trimmed.startsWith("```")) {
            return trimmed;
        }

        int firstNewline = trimmed.indexOf('\n');
        if (firstNewline < 0) {
            // Only a fence line, nothing else — nothing to parse
            return trimmed;
        }

        String afterOpeningFence = trimmed.substring(firstNewline + 1);

        // Find closing fence — search from after the opening fence
        int closingFence = afterOpeningFence.lastIndexOf("```");
        if (closingFence > 0) {
            // Normal case: both opening and closing fences present
            return afterOpeningFence.substring(0, closingFence).strip();
        } else {
            // Truncated case: no closing fence — return what we have after the opening
            log.warn("Gemini response had no closing markdown fence — response may have been truncated");
            return afterOpeningFence.strip();
        }
    }

    private ReportAnalysis parseResponse(String json) {
        try {
            return objectMapper.readValue(json, ReportAnalysis.class);
        } catch (Exception e) {
            log.error("Could not deserialise Gemini JSON. Raw text:\n{}", json, e);
            throw new ReportAnalysisException("AI response format was unexpected. Please try again.", e);
        }
    }

    private static RestTemplate buildRestTemplate() {
        var factory = new org.springframework.http.client.SimpleClientHttpRequestFactory();
        factory.setConnectTimeout(10_000);   // 10 s to open connection
        factory.setReadTimeout(60_000);      // 60 s to receive response (Gemini can be slow)
        return new RestTemplate(factory);
    }
}
